### ISSUE TITLE
Problem with button size on iOs 11

### ISSUE THREAD

**Issue by fuzzball1980** [sudeepjaiswal/ASJOverflowButton#10]
Hi, on iOs 11 the overflow button image is not resized properly and there is no way to add a constraint on the initialization I have made this modification to support my case but I believe there should be a way to initialize  ASJOverflowButton with  a custom button and then set the items.

By the way nice works! It saved me a lot of time!

- (void)setupCustomView
{
  // UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
  
    UIButton *button = nil;
    if (@available(iOS 11.0, *)) {
        button = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 25, 25)];
        [button.widthAnchor constraintEqualToConstant:25].active = YES;
        [button.heightAnchor constraintEqualToConstant:25].active = YES;
    } else {
        button = [UIButton buttonWithType:UIButtonTypeCustom];
    }
    
  button.frame = CGRectMake(0.0f, 0.0f, 44.0f, 44.0f);
  button.autoresizingMask = self.autoresizingMasks;
  [button setImage:_buttonImage forState:UIControlStateNormal];
  [button addTarget:self action:@selector(buttonTapped:) forControlEvents:UIControlEventTouchUpInside];
  
  self.customView = button;
}

**Comment by sdpjswl** [comment]
Added new init method that will allow you to pass custom UIButton. Although providing action for custom button is not required, no harm will occur if you do. It is handled internally.
