### ISSUE TITLE
Overflow menu shadow is stretched in iOS 10

### ISSUE THREAD

**Issue by BrandonCharity** [sudeepjaiswal/ASJOverflowButton#2]
It looks like the backing shadow view of the Overflow menu is stretched and distorted in iOS 10.  I have only one item added to the Overflow menu.  Please see the image.

<img width="173" alt="screen shot 2016-09-22 at 11 11 52 am" src="https://cloud.githubusercontent.com/assets/8588589/18760318/67e45306-80b5-11e6-8a9e-398361e5c33c.png">

**Comment by sdpjswl** [comment]
I have not yet upgraded to Xcode 8/iOS 10 yet but will do so soon and test this issue.

**Comment by sdpjswl** [comment]
I'll try to get this done by this weekend.

**Comment by sdpjswl** [comment]
@BrandonCharity 
@piernic

Fixed in [release 1.5](https://cocoapods.org/pods/ASJOverflowButton). Please update whether the fix works for you.

**Comment by piernic** [comment]
It work for me :) Thx for fast response ;)

**Comment by sdpjswl** [comment]
Great! :)
